### ISSUE TITLE
Contract voting and updates

### ISSUE THREAD

**Issue by etkirsch** [etkirsch/cnd-mean#13]
Currently, voting for an episode calls $update when the user actually changes vote. However, this saves *the current session's data* to the database rather than just performing an update on that specific field. Is there a way to get the contract directive to exclusively update that vm.episode.attendees.contractVote field, and nothing else?

**Comment by Tyroche** [comment]
I see the issue -- I'll look into it. 

Might just require a specific API endpoint, but I don't really prefer that solution.

**Comment by etkirsch** [comment]
I think the answer is to do one of two things, both through mongoose.

1. Alter the Episode Model and give it a `HasMany` relationship to a second model which contains User, Character, and Vote information, say `EpisodeVote` or something. When the user votes, just run `episodeVote.$update();` I think this may be the most direct course of action but I don't like having all of these EpisodeVote models just sitting in the database unnecessarily.

2. Alter the Episode Server Controller and give it a `exports.updateVote` function to only update a specified field and not the whole model, thereby eliminating the need for an EpisodeVote Model.
